/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    cs: [
      {
          type: 'autogenerated',
          dirName: 'cs',
      },
    ],
    C: [
        {
            type: 'autogenerated',
            dirName: 'C++'
        }
    ],
    Algorithms: [
        {
            type: 'autogenerated',
            dirName: 'Algorithms',
        },
    ],
    Overseas: [
        {
            type: 'autogenerated',
            dirName: 'Overseas',
        },
    ],
    OJ: [
        {
            type: 'autogenerated',
            dirName: 'OJ',
        },
    ],
    SDE: [
        {
            type: 'autogenerated',
            dirName: 'SDE',
        },
    ],
    AI: [
        {
            type: 'autogenerated',
            dirName: 'AI',
        },
    ],
};

module.exports = sidebars;
